'use strict';

module.exports = {
  'https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.9/es5-shim.min.js': [
    'chrome <= 12',
    'chrome mobile <= 12',
    'chrome mobile ios <= 12',
    'firefox <= 20',
    'firefox mobile <= 20',
    'ie <= 9',
    'ie mobile <= 9',
    'opera <= 12',
    'safari <= 5',
    'mobile safari <= 5',
    'samsung internet <= 1',
  ],
  'https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.1/es6-shim.min.js': [
    'chrome <= 51',
    'chrome mobile <= 51',
    'chrome mobile ios <= 51',
    'edge <= 13',
    'edge mobile <= 13',
    'firefox <= 44',
    'firefox mobile <= 44',
    'ie <= 11',
    'ie mobile <= 11',
    'safari <= 9',
    'mobile safari <= 9',
    'samsung internet <= 2',
  ],
  'https://unpkg.com/es7-shim@latest/dist/es7-shim.min.js': [
    'chrome <= 50',
    'chrome mobile <= 50',
    'chrome mobile ios <= 50',
    'edge <= 14',
    'edge mobile <= 14',
    'firefox <= 46',
    'firefox mobile <= 46',
    'ie <= 11',
    'ie mobile <= 11',
    'safari <= 10',
    'mobile safari <= 10',
    'samsung internet <= 3',
  ],
  'https://cdnjs.cloudflare.com/ajax/libs/fetch/1.0.0/fetch.min.js': [
    'chrome <= 41',
    'chrome mobile <= 41',
    'chrome mobile ios <= 41',
    'edge <= 13',
    'edge mobile <= 13',
    'firefox <= 38',
    'firefox mobile <= 38',
    'ie <= 11',
    'ie mobile <= 11',
    'safari <= 9',
    'mobile safari <= 9',
    'samsung internet <= 3',
  ],
};
